### ISSUE TITLE
assume NFS server configure to export /srv/nfs

### ISSUE THREAD

**Issue by tdovan** [williamcaban/openshift-lab#2]
hi, can you explain what you mean by NFS server configure to export /srv/nfs ?
do I need to install a local nfs_server locally or just a nfs_client that point to a remote nfs_server exporting /srv/nfs ?
thanks

**Comment by williamcaban** [comment]
If you are referring to https://github.com/williamcaban/openshift-lab/blob/master/inventory-host-aio-TEMPLATE.yaml#L15 it means this particular deployment is using the local node as NFS as per https://github.com/williamcaban/openshift-lab/blob/master/inventory-host-aio-TEMPLATE.yaml#L289 and it will use that path for the NFS exports it will create.
